### ISSUE TITLE
Could not build the application for the simulator.

### ISSUE THREAD

**Issue by jpsantosbh** [geweald/flutter_onfido#4] opened 2021-05-21 02:08 UTC
I'm trying to run the application in the simulator launching it from the Android Visual Studio. 

```Launching lib/main.dart on iPhone 12 Pro in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                            2.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    warning: [CP] Unable to find matching .xcframework slice in '/Users/joaopaulosantos/Development/civic/onfido_test_app/ios/Pods/Onfido/Onfido.xcframework Onfido framework ios-i386_x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64 x86_64 i386).
    /Users/joaopaulosantos/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_onfido-0.2.0/ios/Classes/OnfidoSdk.swift:2:8: error: no such module 'Onfido'
    import Onfido
           ^
    /Users/joaopaulosantos/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_onfido-0.2.0/ios/Classes/OnfidoSdk.swift:2:8: error: no such module 'Onfido'
    import Onfido
           ^
    /Users/joaopaulosantos/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_onfido-0.2.0/ios/Classes/OnfidoSdk.swift:2:8: error: no such module 'Onfido'
    import Onfido
           ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
    note: Removed stale file '/Users/joaopaulosantos/Library/Developer/Xcode/DerivedData/Runner-efufydbfixpattaksvahqtdetfgr/Build/Products/Debug-iphonesimulator/Runner.app'

    note: Removed stale file '/Users/joaopaulosantos/Library/Developer/Xcode/DerivedData/Runner-efufydbfixpattaksvahqtdetfgr/Build/Products/Debug-iphonesimulator/Pods_Runner.framework'

    note: Removed stale file '/Users/joaopaulosantos/Library/Developer/Xcode/DerivedData/Runner-efufydbfixpattaksvahqtdetfgr/Build/Products/Debug-iphonesimulator/flutter_onfido/flutter_onfido.framework'


Could not build the application for the simulator.
Error launching application on iPhone 12 Pro.
```

My Flutter doctor output:
```[✓] Flutter (Channel stable, 2.2.0, on macOS 11.2.3 20D91 darwin-x64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.0)
[✓] Connected device (2 available)

• No issues found!```

**Comment by geweald** [comment] 2021-06-02 11:07
Hi @jpsantosbh have you resolved the issue? I cannot reproduce it. Have you tried to upgrade flutter, clear Pods folder, run `pod repo update` or `pod update`, run `flutter clean`?

**Comment by fryette** [comment] 2021-06-15 17:44
Have absolutely the same error....week ago everything was fine and with new flutter get that issue

**Comment by fryette** [comment] 2021-06-16 07:08
To resolve the issue need to add to your podfile
```  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end

**Comment by fryette** [comment] 2021-07-07 16:59
The latest version seems to work.
Thanks!
I think you can close the issue

**Closed** 2021-07-12 11:25 UTC
